### ISSUE TITLE
Cause: execute-only (no-read) memory access error; likely due to data in .text.

### ISSUE THREAD

**Issue by shuajinanhai** [Rprop/And64InlineHook#5]
on android10.0  targetSdkVersion 29  arm64-v8a
#01 pc 0000000000004880 /data/app/WXW.Hook-LkVDwH8X8qf3LeKNEPrzHg==/lib/arm64/libarm_64.so (A64HookFunctionV+100) (BuildId: 971089d04383d33201a35816448148fd814565f1)
#02 pc 00000000000051d8 /data/app/WXW.Hook-LkVDwH8X8qf3LeKNEPrzHg==/lib/arm64/libarm_64.so (A64HookFunction+80) (BuildId: 971089d04383d33201a35816448148fd814565f1)

**Comment by liuyou** [comment]
我提交了个 pull resuests
